#Based on python gitlab CI template
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  
lint:
  script:
  - pip install -r dev-requirements.txt
  - find . -iname "*.py" | fgrep -v venv | fgrep -v tox  | xargs pylint --suggestion-mode=n
  - black --check --exclude="venv|.tox" .

test_3_6:
  image: python:3.6 
  script:
  - pip install tox
  - tox --version
  - tox -e py36

test_3_7:
# image: python:3.7  #NOTE:Latest is currently 3.7
  script:
  - pip install tox
  - tox --version
  - tox -e py37

security:
 script:
 - pip install safety
 - safety check # TODO: -r requirements.txt
