#Based on python gitlab CI template
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

code_ style:
  script:
  - pip install -r dev-requirements.txt
  - find . -iname "*.py" | fgrep -v venv | fgrep -v tox  | xargs pylint --suggestion-mode=n
  - black --check --exclude="venv|.tox" .
  - pydocstyle grid/* -ve
  - pydocstyle test/* -ve
  only:
  - merge_requests
  - master

static_type_check:
  script:
  - pip install -r dev-requirements.txt
  - find . -type f -name "*.py" | grep -Ev "venv|tox|test" | xargs mypy --strict
  only:
  - merge_requests
  - branch

test_3_6:
  image: python:3.6
  script:
  - pip install tox -U
  - tox --version
  - tox -e py36
  only:
  - merge_request
  - branches

test_3_7:
#  image: python:3.7  # NOTE: latest is currently 3.7
  script:
  - pip install tox -U
  - tox --version
  - tox -e py37  # Possible failure when 3.8 is released
  only:
  - merge_request
  - branches

smoke_test:
  script:
  - printf "Check if Latest smoke test is same day as commit (run smoke_test.sh on failure)\\n"
  - cat .smoke_test_results.txt
  - printf "Last git commit date (UTC) -> %s\\n" "$(git log -1 --format="%at" | xargs -I{} date -u -d @{} --iso-8601)"
  - grep "Smoke Test PASSED -> $(git log -1 --format="%at" | xargs -I{} date -u -d @{} --iso-8601)" .smoke_test_results.txt
  only:
  - merge_request
  - master

security:
  script:
  - pip install safety -U
  - safety check -r requirements.txt  --full-report
  only:
    - merge_requests
    - master
